version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"


# The new volumes key mounts the project directory (current directory) on the host to /code inside the container, 
# allowing you to modify the code on the fly, without having to rebuild the image. 
# The environment key sets the FLASK_DEBUG environment variable, which tells flask run to run in development mode 
# and reload the code on change. This mode should only be used in development.
